name: Build and Deploy Sphinx Docs via GitHub Actions

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  # 1) Build your Sphinx docs
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx==7.1.2
          pip install -r docs/requirements.txt  # Make sure this file exists

      - name: Build Sphinx HTML
        run: |
          cd docs
          make html  # Adjust if your Makefile is elsewhere

      - name: Upload artifact for Pages
        uses: actions/upload-artifact@v4
        with:
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # <--- The branch to deploy to
          folder: docs/build/html # <--- Where your built docs live
          token: ${{ secrets.GITHUB_TOKEN }} # <--- Make sure to pass the GITHUB_TOKEN
