name: Deploy Sphinx Docs via GitHub Actions

on:
  # Rebuild docs on every push to 'main' or on pull requests
  push:
    branches: ["main"]
  pull_request:

permissions:
  # Required so we can upload and deploy Pages artifacts
  contents: read
  pages: write
  id-token: write

jobs:
  # 1) Build the docs
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx==7.1.2
          pip install -r docs/requirements.txt   # Adjust if needed

      - name: Build Sphinx HTML
        run: |
          cd docs
          make html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the built HTML so the next job can deploy it
          path: docs/build/html

  # 2) Deploy to GitHub Pages
  deploy:
    # Marks this job as the one that deploys to your "GitHub Pages" environment
    environment:
      name: github-pages
      # The 'url' field is automatically set by the deploy action,
      # but you can reference steps.deployment.outputs.page_url if needed
    runs-on: ubuntu-latest

    needs: build # This job depends on the 'build' job finishing first

    steps:
      - name: Download artifact
        uses: actions/download-pages-artifact@v1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          # Deploy *everything* from the downloaded artifact to your Pages site
          path: .
