name: Publish Documentation to GitHub Pages

on:
  push:
    branches:
      - main # Ensures the action runs on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Ensure compatibility with your project requirements

      - name: Install Sphinx and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx==${{ env.SPHINX_VERSION }}
          pip install -r docs/requirements.txt  # Adjust path if necessary

      - name: Build HTML with Sphinx
        run: |
          cd docs  # Adjust path to where your Sphinx Makefile is located
          make html

      - name: Upload HTML to artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: docs/build/html/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: sphinx-docs
          path: docs/build/html/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # Target branch to deploy to
          folder: docs/build/html/ # The folder path to deploy
          clean: true # Optional: Cleans the deployment branch except for the .git directory
